__author__ = 'skye 2017-11-26'
# coding=utf-8

s = ['musicday', 'limitmission50classic', 'halloween1', 'adventure', 'gonewind',
			'aladdin', 'rockinnewyear', 'italianspice', 'limitmission41', 'limitmission32',
			'captaindarrylhook', 'limitmission45', 'limitmission46', 'limitmission18',
			'limitmission34', 'limitmission21', 'samuraidarrylandlobster', 'limitmission28', 'singingintherain',
			'limitmission47', 'limitmission47', 'limitmission47',
			'limitmission65', 'limitmission65', 'limitmission65',
			'secretsofindia', 'secretsofindia', 'secretsofindia',
			'trickorsqueak', 'trickorsqueak', 'trickorsqueak', 'trickorsqueak',
			'limitmission51', 'limitmission68classic', 'sammythesongbirdclassic',
			'limitmission85', 'limitmission85','limitmission85', 'limitmission85',
			'limitmission87', 'limitmission87', 'limitmission87',
			'limitmission86', 'limitmission86', 'limitmission86', 'limitmission86',
			'limitmission88', 'limitmission88', 'limitmission88',
			'limitmission89', 'limitmission89', 'limitmission89', 'limitmission89classic',
			'limitmission90', 'limitmission90', 'limitmission90','limitmission90',
			'limitmission91', 'limitmission91', 'limitmission91', 'limitmission91',
			'limitmission92', 'limitmission92', 'limitmission92', 'limitmission92',
			'limitmission93', 'limitmission93', 'limitmission93',
			'limitmission94', 'limitmission94', 'limitmission94', 'limitmission94',
			'limitmission95', 'limitmission95', 'limitmission95', 'limitmission95',
			'limitmission96', 'limitmission96', 'limitmission96', 'limitmission96',
			'limitmission97', 'limitmission97', 'limitmission97', 'limitmission97',
			'limitmission98', 'limitmission98', 'limitmission98', 'limitmission98',
			'limitmission99', 'limitmission99', 'limitmission99', 'limitmission99',
			'limitmission100', 'limitmission100', 'limitmission100', 'limitmission100',
			'limitmission101', 'limitmission101', 'limitmission101', 'limitmission101',
			'limitmission102', 'limitmission102', 'limitmission102','limitmission102',
			'limitmission103', 'limitmission103', 'limitmission103','limitmission103',
			'turkeytraditions',  'turkeytraditions', 'turkeytraditions', 'happycanary', 'happycanary', 'happycanary',
			'santasworkshop','santasworkshop', 'santasworkshop', 'santaismia',
			'loveinvenice','loveinvenice', 'loveinvenice',
			'theincrediblejourney','theincrediblejourney', 'theincrediblejourney',
			'gumballmania', 'gumballmania', 'gumballmania', 'dazzlingdollshopclassic',
			'tacotrucktour', 'tacotrucktour', 'tacotrucktour',
			'nougatnobelprize', 'nougatnobelprize', 'nougatnobelprize', 'fathersdayclassic',
			'onceuponamacaron', 'onceuponamacaron','onceuponamacaron', 'onceuponamacaron',
			'pelicanandduck','pelicanandduck', 'pelicanandduck', 'limitmission55classic',
			'frozenfarm', 'frozenfarm', 'frozenfarm', 'countrycarnival',
			'countrycarnival', 'countrycarnival', 'familyfarmsummerfest','familyfarmsummerfest', 'familyfarmsummerfest',
			'familyfarmsummerfest', 'spadaywithgrannyclassic', 'firstdayofschool',
			'firstdayofschool', 'firstdayofschool', 'firstdayofschool',
			'halloweenstuffiesinvasion', 'halloweenstuffiesinvasion','halloweenstuffiesinvasion', 'halloweenstuffiesinvasion',
			'creamcheesevillage', 'creamcheesevillage', 'creamcheesevillage', 'trickorsqueakclassic', 'howafoxstolechristmas',
			'howafoxstolechristmas', 'howafoxstolechristmas', 'howafoxstolechristmas', 'grannysweddingadventure',
			'grannysweddingadventure', 'grannysweddingadventure', 'grannysweddingadventure', 'christmaseveadventure',
			'christmaseveadventure', 'christmaseveadventure', 'christmaseveadventure', 'ringinthenewyear', 'ringinthenewyear',
			'ringinthenewyear', 'ringinthenewyear', 'fountainofyouthclassic',
			'thelavaarcher', 'thelavaarcher', 'thelavaarcher', 'cashmeregoatclassic', 'feliciasvalentine', 'feliciasvalentine',
			'feliciasvalentine', 'feliciasvalentine', 'thefamousfarmer',
			'thefamousfarmer', 'thefamousfarmer', 'thefamousfarmer',
			'thegreateasterchipmumk', 'thegreateasterchipmumk', 'thegreateasterchipmumk', 'thegreateasterchipmumk',
			'millysmacandcheese', 'millysmacandcheese', 'millysmacandcheese','millysmacandcheese',
			'croissantcomedy', 'croissantcomedy', 'croissantcomedy',
			'limitmission75classic', 'limitmission104', 'limitmission104', 'limitmission104', 'limitmission104',
			'hotpot',  'hotpot', 'hotpot', 'hotpot', 'elvesonholidayclassic',
			'mothersdayoasis', 'mothersdayoasis', 'mothersdayoasis', 'mothersdayoasis',
			'summersorbetparty', 'summersorbetparty', 'summersorbetparty','summersorbetparty', 'summersorbetparty',
			'darrylvstheporridge', 'darrylvstheporridge', 'darrylvstheporridge', 'darrylvstheporridge', 'darrylvstheporridge', 'darrylvstheporridge',
			'fallingforafoal', 'fallingforafoal', 'fallingforafoal', 'fallingforafoal', 'fallingforafoal', 'fallingforafoal',
			'tashaspolarplunge', 'tashaspolarplunge', 'tashaspolarplunge', 'tashaspolarplunge', 'tashaspolarplunge', 'tashaspolarplunge',
			'asoakingsongkranfestival',  'asoakingsongkranfestival', 'asoakingsongkranfestival', 'asoakingsongkranfestival','asoakingsongkranfestival', 'asoakingsongkranfestival',
			'autumnmaskedgala',  'autumnmaskedgala', 'autumnmaskedgala', 'autumnmaskedgala', 'autumnmaskedgala',
			'darrylandthespellingbee', 'darrylandthespellingbee', 'darrylandthespellingbee', 'darrylandthespellingbee', 'darrylandthespellingbee',
			'puffeduppatty', 'puffeduppatty', 'puffeduppatty', 'puffeduppatty', 'puffeduppatty',
			'henryhammerheadslifepurpose', 'henryhammerheadslifepurpose','henryhammerheadslifepurpose', 'henryhammerheadslifepurpose','henryhammerheadslifepurpose',
			'entrepreneurelephantshrew', 'entrepreneurelephantshrew', 'entrepreneurelephantshrew', 'entrepreneurelephantshrew', 'entrepreneurelephantshrew',
			'tobyandfeliciasfirstfight', 'tobyandfeliciasfirstfight', 'tobyandfeliciasfirstfight', 'tobyandfeliciasfirstfight','tobyandfeliciasfirstfight',
			'tobyssurpriseparty', 'tobyssurpriseparty', 'tobyssurpriseparty', 'tobyssurpriseparty','tobyssurpriseparty','tobyssurpriseparty',
			'averymerrychristmas', 'averymerrychristmas','averymerrychristmas', 'averymerrychristmas', 'averymerrychristmas',
			'darrylsgopherfriends',  'darrylsgopherfriends','darrylsgopherfriends', 'darrylsgopherfriends', 'darrylsgopherfriends',
			'tempuramasterdarryl', 'tempuramasterdarryl','tempuramasterdarryl', 'tempuramasterdarryl', 'tempuramasterdarryl',
			'darrylsspookynight', 'darrylsspookynight', 'darrylsspookynight','darrylsspookynight', 'darrylsspookynight',
			'thecrepeketeer',  'thecrepeketeer', 'thecrepeketeer', 'thecrepeketeer', 'thecrepeketeer',
			'bondingovermeatballs', 'bondingovermeatballs', 'bondingovermeatballs', 'bondingovermeatballs','bondingovermeatballs','bondingovermeatballs',
			'hauntedfogtree', 'hauntedfogtree', 'hauntedfogtree', 'hauntedfogtree','hauntedfogtree','hauntedfogtree',
			'tashasmagicalmessageparti', 'tashasmagicalmessageparti', 'tashasmagicalmessageparti', 'tashasmagicalmessageparti','tashasmagicalmessageparti','tashasmagicalmessageparti',
			'limitmission106', 'limitmission106', 'limitmission106','limitmission106',
			'limitmission107', 'limitmission107', 'limitmission107','limitmission107',
			'limitmission108', 'limitmission108', 'limitmission108','limitmission108',
			'limitmission109', 'limitmission109', 'limitmission109', 'limitmission109',
			'limitmission110', 'limitmission110', 'limitmission110','limitmission110',
			'limitmission112', 'limitmission112', 'limitmission112','limitmission112',
			'limitmission113', 'limitmission113', 'limitmission113','limitmission113',
			'limitmission114', 'limitmission114', 'limitmission114','limitmission114',
			'limitmission115', 'limitmission115', 'limitmission115', 'limitmission115',
			'limitmission116', 'limitmission116', 'limitmission116', 'limitmission116',
			'limitmission117', 'limitmission117', 'limitmission117', 'limitmission117',
			'limitmission118', 'limitmission118', 'limitmission118', 'limitmission118',
			'limitmission119', 'limitmission119', 'limitmission119', 'limitmission119',
			'limitmission120', 'limitmission120', 'limitmission120','limitmission120',
			'limitmission122', 'limitmission122', 'limitmission122', 'limitmission122',
			'limitmission124', 'limitmission124', 'limitmission124', 'limitmission124', 'limitmission124',
			'limitmission125', 'limitmission125', 'limitmission125','limitmission125', 'limitmission125',
			'limitmission128', 'limitmission128', 'limitmission128','limitmission128',
			'limitmission129', 'limitmission129', 'limitmission129', 'limitmission129', 'limitmission129',
			'limitmission130', 'limitmission130', 'limitmission130', 'limitmission130', 'limitmission130',
			'limitmission132', 'limitmission132', 'limitmission132', 'limitmission132', 'limitmission132',
			'limitmission133', 'limitmission133', 'limitmission133', 'limitmission133', 'limitmission133',
			'limitmission134', 'limitmission134', 'limitmission134', 'limitmission134', 'limitmission134', 'limitmission134',
			'limitmission135', 'limitmission135', 'limitmission135','limitmission135', 'limitmission135', 'limitmission135',
			'limitmission136', 'limitmission136', 'limitmission136','limitmission136', 'limitmission136',
			'limitmission137', 'limitmission137', 'limitmission137','limitmission137', 'limitmission137', 'limitmission137',
			'limitmission140', 'limitmission140', 'limitmission140', 'limitmission140', 'limitmission140', 'limitmission140',
			'limitmission141', 'limitmission141', 'limitmission141', 'limitmission141', 'limitmission141', 'limitmission141',
			'limitmission142', 'limitmission142', 'limitmission142', 'limitmission142', 'limitmission142', 'limitmission142',
			'limitmission143','limitmission143','limitmission143','limitmission143','limitmission143','limitmission143',
			'limitmission144','limitmission144','limitmission144','limitmission144','limitmission144','limitmission144',
			'limitmission145','limitmission145','limitmission145','limitmission145','limitmission145','limitmission145',
			'limitmission146','limitmission146','limitmission146','limitmission146','limitmission146','limitmission146',
			'limitmission147','limitmission147','limitmission147','limitmission147','limitmission147','limitmission147',
			'limitmission148','limitmission148','limitmission148','limitmission148','limitmission148','limitmission148',
			'limitmission149','limitmission149','limitmission149','limitmission149','limitmission149','limitmission149',
			'limitmission150','limitmission150','limitmission150','limitmission150','limitmission150','limitmission150',
			'limitmission151','limitmission151','limitmission151','limitmission151','limitmission151','limitmission151',
			'limitmission152','limitmission152','limitmission152','limitmission152','limitmission152','limitmission152',
			'limitmission153','limitmission153','limitmission153','limitmission153','limitmission153','limitmission153',
			'limitmission154','limitmission154','limitmission154','limitmission154','limitmission154','limitmission154',
			'limitmission155','limitmission155','limitmission155','limitmission155','limitmission155','limitmission155',
			'worldbaconfestival','worldbaconfestival','worldbaconfestival','worldbaconfestival',
			'midsummerinscandinavia','midsummerinscandinavia','midsummerinscandinavia','midsummerinscandinavia',
			'kidofthejungle','kidofthejungle','kidofthejungle','kidofthejungle',
			'thefennecfirefighters','thefennecfirefighters','thefennecfirefighters','thefennecfirefighters',
			'ottersdayout','ottersdayout','ottersdayout','ottersdayout',
			'duckscansurftoo', 'duckscansurftoo', 'duckscansurftoo','duckscansurftoo','limitmission112classic']
print('s =', s)
s2 = set(s)
print('s2 =', s2)
s = list(s2)
s.sort()
print('s =', s)
